import { Head, usePage } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import {
    LuBell, LuCalendarDays, LuChartNoAxesCombined, LuChevronDown, LuCircleHelp,
    LuClock3, LuCreditCard, LuGrid2X2, LuHeart, LuHouse, LuMenu, LuPlus,
    LuSearch, LuSettings, LuSparkles, LuStar, LuUsers, LuX,
} from 'react-icons/lu';
import Logo from '../../../../src/components/Logo';

const colors = ['#5b50f5', '#8b7cf6', '#60a5fa', '#2dd4bf', '#94a3b8'];
const labels = { calendar: 'Calendario', crm: 'Clientes', payments: 'Pagos', forms: 'Formularios', reports: 'Reportes', resources: 'Recursos', staff: 'Personal' };

export default function Dashboard({ business, metrics = {}, dailyBookings = [], recentActivity = [], upcomingBookings = [], serviceDistribution = [], customers = [] }) {
    const { auth } = usePage().props;
    const [active, setActive] = useState('Inicio');
    const [period, setPeriod] = useState('Últimos 7 días');
    const [search, setSearch] = useState('');
    const [quickOpen, setQuickOpen] = useState(false);
    const settings = business?.settings || {};
    const capabilities = business?.capabilities || {};
    const enabled = settings.features || ['calendar', 'crm', 'forms', 'reports'];
    const name = auth?.user?.name?.split(' ')[0] || 'bienvenido';
    const currency = business?.currency || 'COP';
    const nav = [
        ['Inicio', LuHouse, true], ['Calendario', LuCalendarDays, enabled.includes('calendar')],
        ['Reservas', LuCalendarDays, true], ['Clientes', LuUsers, enabled.includes('crm')],
        ['Servicios', LuSparkles, true], ['Personal', LuUsers, capabilities.requires_staff || enabled.includes('staff')],
        ['Recursos', LuGrid2X2, enabled.includes('resources')], ['Pagos', LuCreditCard, enabled.includes('payments')],
        ['Promociones', LuStar, enabled.includes('promotions')], ['Reportes', LuChartNoAxesCombined, enabled.includes('reports')],
        ['Integraciones', LuGrid2X2, enabled.includes('integrations')], ['Configuración', LuSettings, true],
    ].filter(([, , visible]) => visible);
    const filteredCustomers = useMemo(() => customers.filter((customer) => customer.name.toLowerCase().includes(search.toLowerCase())), [customers, search]);
    const maxBookings = Math.max(1, ...dailyBookings.map((item) => item.count));
    const money = new Intl.NumberFormat('es-CO', { style: 'currency', currency, maximumFractionDigits: 0 });
    const rating = Number(metrics.rating || 0);

    return <div className="min-h-screen bg-[#f7f9fd] text-[#11184b]">
        <Head title={`${business?.name || 'Noryvaq'} · Dashboard`} />
        <aside className="fixed inset-y-0 left-0 z-30 hidden w-[228px] flex-col border-r border-slate-100 bg-white px-4 py-6 lg:flex">
            <Brand />
            <nav className="mt-10 space-y-1">{nav.map(([label, Icon]) => <button key={label} type="button" onClick={() => setActive(label)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium transition ${active === label ? 'bg-[#f0edff] !text-[#5145e5]' : 'text-slate-600 hover:bg-[#5b50f5] hover:!text-white'}`}><Icon size={19} strokeWidth={1.8} />{label}</button>)}</nav>
            <div className="mt-auto space-y-4">
                <div className="rounded-2xl bg-gradient-to-br from-[#e7e1ff] to-[#cfc6ff] p-4"><p className="text-sm font-bold text-[#11184b]">Lleva tu negocio a otro nivel</p><p className="mt-2 text-xs leading-5 text-indigo-900/70">Activa más módulos y haz crecer tu comunidad.</p><button type="button" className="mt-4 rounded-lg bg-white px-3 py-2 text-xs font-bold text-[#5145e5] shadow-sm hover:bg-[#5b50f5] hover:text-white">Ver planes →</button></div>
                <div className="flex items-center gap-3 rounded-2xl border border-slate-100 p-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-indigo-100 font-bold text-[#5b50f5]">{business?.name?.[0] || 'N'}</div><div className="min-w-0"><p className="truncate text-sm font-bold">{business?.name || 'Noryvaq'}</p><p className="text-xs text-slate-500">Plan Pro · Demo</p></div><LuChevronDown className="ml-auto shrink-0 text-slate-500" size={16} /></div>
            </div>
        </aside>

        <main className="lg:pl-[228px]">
            <header className="sticky top-0 z-20 flex h-[72px] items-center gap-4 border-b border-slate-100 bg-white/95 px-4 backdrop-blur sm:px-8">
                <div className="lg:hidden"><Brand compact /></div>
                <div className="relative max-w-xl flex-1"><LuSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-11 w-full rounded-xl border-0 bg-[#f7f8fc] pl-11 pr-4 text-sm outline-none ring-1 ring-transparent placeholder:text-slate-400 focus:ring-[#5b50f5]" placeholder="Buscar clientes, reservas, servicios..." /></div>
                <button type="button" className="hidden rounded-full p-2 text-slate-500 hover:bg-[#5b50f5] hover:text-white sm:block"><LuBell size={20} /></button><button type="button" className="hidden rounded-full p-2 text-slate-500 hover:bg-[#5b50f5] hover:text-white sm:block"><LuCircleHelp size={20} /></button><div className="hidden h-8 w-px bg-slate-200 sm:block" /><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-amber-200 to-rose-200 text-sm font-bold text-slate-700">{name[0]}</div><div className="hidden text-left sm:block"><p className="text-sm font-bold text-slate-800">{auth?.user?.name || 'Usuario'}</p><p className="text-xs text-slate-500">Administrador</p></div><LuChevronDown className="hidden text-slate-500 sm:block" size={16} /></div>
            </header>

            <div className="mx-auto max-w-[1450px] px-4 py-6 pb-28 sm:px-8 lg:px-10 lg:py-9">
                <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-slate-500">Lunes, 22 de septiembre de 2026</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#11184b] sm:text-4xl">Hola, {name} <span className="text-amber-400">👋</span></h1><p className="mt-2 text-sm text-slate-500">Aquí tienes un resumen de tu negocio.</p></div><button type="button" className="flex items-center gap-3 self-start rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 shadow-sm hover:border-[#5b50f5] hover:bg-[#5b50f5] hover:!text-white">Lunes, 22 de septiembre de 2026 <LuCalendarDays size={17} /></button></div>

                <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Reservas hoy" value={metrics.bookings_today ?? 0} change="20%" icon={LuCalendarDays} tone="violet" /><Kpi label="Clientes nuevos" value={metrics.new_customers ?? 0} change="12%" icon={LuUsers} tone="blue" /><Kpi label="Ingresos hoy" value={money.format((metrics.revenue_today || 0) / 100)} change="18%" icon={LuCreditCard} tone="cyan" /><Kpi label="Valoración promedio" value={rating ? rating.toFixed(1) : '—'} change={rating ? `${metrics.reviews_count || 0} reseñas` : 'Sin reseñas'} icon={LuStar} tone="pink" rating={rating} /></div>

                {active === 'Inicio' ? <>
                    <div className="mt-6 grid gap-6 xl:grid-cols-[1.55fr_0.9fr]"><ReservationsChart data={dailyBookings} max={maxBookings} period={period} setPeriod={setPeriod} /><Activity items={recentActivity} /></div>
                    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1fr_0.95fr]"><Upcoming items={upcomingBookings} /><Services data={serviceDistribution} total={rangeTotal(serviceDistribution)} /><Customers items={filteredCustomers} /></div>
                    <div className="mt-6 grid gap-6 lg:grid-cols-[1.25fr_0.75fr]"><Promo /><Tip /></div>
                </> : <section className="mt-8 rounded-3xl border border-slate-100 bg-white p-12 text-center shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-50 text-[#5b50f5]"><LuSparkles size={26} /></div><h2 className="mt-5 text-xl font-bold">{active}</h2><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">Esta sección está lista para trabajar con la configuración de {business?.name}.</p><button type="button" onClick={() => setActive('Inicio')} className="mt-6 rounded-xl bg-[#5b50f5] !text-white px-5 py-3 text-sm font-semibold hover:bg-[#4840d2]">Volver al inicio</button></section>}
            </div>
        </main>
        <MobileNav active={active} setActive={setActive} quickOpen={quickOpen} setQuickOpen={setQuickOpen} />
    </div>;
}

function Brand({ compact = false }) { return compact ? <Logo compact /> : <div className="px-2"><Logo /><p className="-mt-1 ml-1 text-[10px] font-medium tracking-wide text-slate-400">Reserva. Conecta. Haz crecer.</p></div>; }
function Kpi({ label, value, change, icon: Icon, tone, rating = 0 }) { const tones = { violet: 'bg-violet-100 text-[#5b50f5]', blue: 'bg-blue-100 text-blue-600', cyan: 'bg-cyan-100 text-cyan-600', pink: 'bg-fuchsia-100 text-fuchsia-600' }; return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-[0_8px_28px_rgba(42,47,90,0.05)]"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tones[tone]}`}><Icon size={20} /></span></div><p className="mt-4 text-3xl font-bold tracking-tight text-[#11184b]">{value}</p>{rating > 0 && <div className="mt-1 flex items-center gap-0.5 text-amber-400">{[1, 2, 3, 4, 5].map((star) => <LuStar key={star} size={14} fill={star <= Math.round(rating) ? 'currentColor' : 'none'} />)}</div>}<p className="mt-2 text-xs"><span className="font-bold text-emerald-500">↑ {change}</span>{!rating && <span className="ml-2 text-slate-400">vs. semana anterior</span>}</p></div>; }
function Card({ title, action, children, className = '' }) { return <section className={`rounded-2xl border border-slate-100 bg-white p-5 shadow-[0_8px_28px_rgba(42,47,90,0.05)] ${className}`}><div className="mb-5 flex items-center justify-between"><h2 className="text-base font-bold text-[#11184b]">{title}</h2>{action}</div>{children}</section>; }
function ReservationsChart({ data, max, period, setPeriod }) { return <Card title="Reservas de los últimos 7 días" action={<select value={period} onChange={(event) => setPeriod(event.target.value)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600 outline-none focus:border-[#5b50f5]"><option>Últimos 7 días</option><option>Últimos 30 días</option><option>Este mes</option></select>}><div className="flex h-52 items-end gap-3 border-b border-slate-100 px-2 pb-0 pt-5 sm:gap-6">{(data.length ? data : [{ label: 'Lun', count: 0 }, { label: 'Mar', count: 0 }, { label: 'Mié', count: 0 }, { label: 'Jue', count: 0 }, { label: 'Vie', count: 0 }, { label: 'Sáb', count: 0 }, { label: 'Dom', count: 0 }]).map((item) => <div className="flex h-full flex-1 flex-col items-center justify-end gap-2" key={item.date || item.label}><div className="w-full max-w-10 rounded-t-lg bg-gradient-to-t from-[#5b50f5] to-[#a79cff] transition-all hover:from-[#4840d2]" style={{ height: `${Math.max(item.count ? 10 : 2, item.count / max * 80)}%` }} title={`${item.count} reservas`} /><span className="text-xs text-slate-500">{item.label}</span></div>)}</div></Card>; }
function Activity({ items }) { return <Card title="Actividad reciente" action={<button type="button" className="text-xs font-bold text-[#5b50f5] hover:text-[#11184b]">Ver todas</button>}><div className="space-y-4">{(items.length ? items : [{ type: 'Aún no hay actividad', detail: 'Cuando recibas reservas aparecerán aquí', time: '' }]).map((item, index) => <div className="flex items-center gap-3" key={`${item.type}-${index}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${item.tone === 'red' ? 'bg-red-50 text-red-500' : 'bg-indigo-50 text-[#5b50f5]'}`}><LuCalendarDays size={17} /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-800">{item.type}</p><p className="truncate text-xs text-slate-500">{item.detail}</p></div><span className="shrink-0 text-[11px] text-slate-400">{item.time}</span></div>)}</div></Card>; }
function Upcoming({ items }) { return <Card title="Próximas reservas" action={<button type="button" className="text-xs font-bold text-[#5b50f5] hover:text-[#11184b]">Ver todas</button>}><div className="space-y-3">{(items.length ? items : [{ time: '--:--', customer: 'No hay reservas próximas', service: 'Crea una nueva reserva', status: 'pending' }]).map((item, index) => <div className="flex items-center gap-3" key={`${item.time}-${index}`}><span className="rounded-lg bg-slate-50 px-2 py-2 text-xs font-bold text-[#11184b]">{item.time}</span><span className="flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-indigo-100 to-cyan-100 text-xs font-bold text-[#5b50f5]">{item.customer?.[0] || '?'}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-800">{item.customer}</p><p className="truncate text-xs text-slate-500">{item.service}</p></div><Status status={item.status} /></div>)}</div></Card>; }
function Status({ status }) { const map = { confirmed: ['Confirmada', 'bg-emerald-50 text-emerald-600'], pending: ['Pendiente', 'bg-orange-50 text-orange-600'], in_progress: ['En curso', 'bg-blue-50 text-blue-600'], completed: ['Completada', 'bg-slate-100 text-slate-600'], cancelled: ['Cancelada', 'bg-red-50 text-red-600'] }; const [label, style] = map[status] || map.pending; return <span className={`rounded-md px-2 py-1 text-[10px] font-bold ${style}`}>{label}</span>; }
function Services({ data, total }) { return <Card title="Distribución de servicios"><div className="flex items-center gap-5"><div className="relative h-36 w-36 shrink-0 rounded-full" style={{ background: donutGradient(data) }}><div className="absolute inset-7 flex flex-col items-center justify-center rounded-full bg-white"><strong className="text-xl text-[#11184b]">{total}</strong><span className="text-[10px] text-slate-500">reservas</span></div></div><div className="min-w-0 flex-1 space-y-2">{(data.length ? data.slice(0, 5) : [{ name: 'Sin datos', percentage: 100 }]).map((item, index) => <div className="flex items-center gap-2 text-xs" key={item.name}><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: colors[index] }} /><span className="min-w-0 flex-1 truncate text-slate-600">{item.name}</span><strong className="text-slate-700">{item.percentage}%</strong></div>)}</div></div></Card>; }
function donutGradient(data) { if (!data.length) return '#e5e7eb'; let start = 0; const parts = data.slice(0, 5).map((item, index) => { const end = start + item.percentage; const part = `${colors[index]} ${start}% ${end}%`; start = end; return part; }); return `conic-gradient(${parts.join(', ')})`; }
function rangeTotal(data) { return data.reduce((sum, item) => sum + (item.count || 0), 0); }
function Customers({ items }) { return <Card title="Clientes" action={<button type="button" className="text-xs font-bold text-[#5b50f5] hover:text-[#11184b]">Ver todos</button>}><div className="mb-4 flex rounded-lg bg-slate-50 p-1 text-xs"><button type="button" className="flex-1 rounded-md bg-white py-2 font-semibold text-[#5b50f5] shadow-sm">Nuevos</button><button type="button" className="flex-1 py-2 text-slate-500">Más frecuentes</button></div><div className="space-y-3">{(items.length ? items.slice(0, 5) : [{ name: 'Aún no hay clientes', time: '' }]).map((item, index) => <div className="flex items-center gap-3" key={`${item.name}-${index}`}><span className="flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-rose-100 to-violet-100 text-xs font-bold text-[#5b50f5]">{item.name[0]}</span><div><p className="text-sm font-semibold text-slate-800">{item.name}</p><p className="text-xs text-slate-400">{item.time}</p></div></div>)}</div></Card>; }
function Promo() { return <div className="flex min-h-36 items-center justify-between overflow-hidden rounded-2xl bg-gradient-to-r from-[#e7e1ff] to-[#c9f5f5] p-6"><div><p className="text-lg font-bold text-[#11184b]">Tu negocio, en todas partes</p><p className="mt-2 max-w-md text-sm text-indigo-900/70">Activa tu app personalizada, comparte tu enlace y recibe más reservas.</p><button type="button" className="mt-4 rounded-lg bg-[#5b50f5] !text-white px-4 py-2 text-xs font-bold hover:bg-[#4840d2]">Ver opciones →</button></div><LuSparkles className="mr-6 hidden text-[#5b50f5]/40 sm:block" size={72} /></div>; }
function Tip() { return <div className="flex min-h-36 items-start gap-4 rounded-2xl bg-[#e4faf4] p-6"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-emerald-500"><LuHeart size={20} /></span><div><p className="font-bold text-[#11184b]">Consejo del día</p><p className="mt-2 text-sm leading-6 text-emerald-900/70">Los negocios que envían recordatorios reducen las cancelaciones y mejoran la experiencia del cliente.</p></div></div>; }
function MobileNav({ active, setActive, quickOpen, setQuickOpen }) { return <><div className="fixed bottom-0 left-0 right-0 z-30 flex items-end justify-around border-t border-slate-100 bg-white/95 px-3 pb-[env(safe-area-inset-bottom)] pt-2 shadow-[0_-8px_24px_rgba(42,47,90,0.08)] lg:hidden"><MobileNavButton label="Inicio" icon={LuHouse} active={active === 'Inicio'} onClick={() => setActive('Inicio')} /><MobileNavButton label="Calendario" icon={LuCalendarDays} active={active === 'Calendario'} onClick={() => setActive('Calendario')} /><button type="button" onClick={() => setQuickOpen(true)} className="-mt-7 flex h-14 w-14 items-center justify-center rounded-full bg-[#5b50f5] text-white shadow-lg shadow-indigo-300"><LuPlus size={28} /></button><MobileNavButton label="Clientes" icon={LuUsers} active={active === 'Clientes'} onClick={() => setActive('Clientes')} /><MobileNavButton label="Más" icon={LuMenu} active={false} onClick={() => setQuickOpen(true)} /></div>{quickOpen && <div className="fixed inset-0 z-40 flex items-end bg-[#11184b]/30 p-4 lg:hidden" onClick={() => setQuickOpen(false)}><div className="w-full rounded-3xl bg-white p-5" onClick={(event) => event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Crear nuevo</h2><button type="button" onClick={() => setQuickOpen(false)}><LuX /></button></div><div className="grid grid-cols-3 gap-3"><QuickAction label="Nueva reserva" icon={LuCalendarDays} /><QuickAction label="Nuevo cliente" icon={LuUsers} /><QuickAction label="Registrar pago" icon={LuCreditCard} /></div></div></div>}</>; }
function MobileNavButton({ label, icon: Icon, active, onClick }) { return <button type="button" onClick={onClick} className={`flex min-w-14 flex-col items-center gap-1 px-2 py-1 text-[10px] font-semibold ${active ? 'text-[#5b50f5]' : 'text-slate-500'}`}><Icon size={20} /><span>{label}</span></button>; }
function QuickAction({ label, icon: Icon }) { return <button type="button" className="flex min-h-20 flex-col items-center justify-center gap-2 rounded-2xl bg-indigo-50 text-xs font-semibold text-[#5b50f5] hover:bg-[#5b50f5] hover:text-white"><Icon size={22} /><span>{label}</span></button>; }
