import {
  LuArrowLeft,
  LuArrowRight,
  LuCalendarDays,
  LuChartNoAxesCombined,
  LuCheck,
  LuChevronDown,
  LuClock3,
  LuGrid2X2,
  LuHeart,
  LuHouse,
  LuLock,
  LuMapPin,
  LuMenu,
  LuPlus,
  LuSearch,
  LuSettings,
  LuSparkles,
  LuStar,
  LuStore,
  LuSun,
  LuUser,
  LuUsers,
  LuX,
} from 'react-icons/lu';

const icons = {
  arrow: LuArrowRight,
  arrowLeft: LuArrowLeft,
  calendar: LuCalendarDays,
  check: LuCheck,
  chevron: LuChevronDown,
  clock: LuClock3,
  close: LuX,
  chart: LuChartNoAxesCombined,
  grid: LuGrid2X2,
  heart: LuHeart,
  home: LuHouse,
  menu: LuMenu,
  people: LuUsers,
  pin: LuMapPin,
  plus: LuPlus,
  search: LuSearch,
  settings: LuSettings,
  star: LuStar,
  spark: LuSparkles,
  store: LuStore,
  sun: LuSun,
  lock: LuLock,
  user: LuUser,
  x: LuX,
};

export default function Icon({ name, size = 18, strokeWidth = 1.8, className = '' }) {
  const IconComponent = icons[name] || LuSparkles;
  return <IconComponent className={`icon ${className}`} size={size} strokeWidth={strokeWidth} aria-hidden="true" />;
}
